destroy_node_data – flist
destroy_node_data Subroutine
9 statements
Source File
private impure elemental subroutine destroy_node_data(me)
destroy the data in the node.
Type Bound
node
Arguments
Type Intent Optional Attributes Name
class(node), intent(inout) :: me
Called by
Source Code
    impure elemental subroutine destroy_node_data(me)
    implicit none
    class(node),intent(inout) :: me
    if (allocated(me%key)) deallocate(me%key)
    if (me%destroy_on_delete) then
        ! deallocates the pointer (and call any finalizer)
        ! (otherwise, it is up to the caller to do this)
        if (associated(me%value)) deallocate(me%value)
    end if
    nullify(me%value)
    end subroutine destroy_node_data
Call graph
destroy_node calls destroy_node_data, destroy_node
remove_by_pointer calls destroy_node_data
add_pointer calls remove_by_pointer
destroy_list calls destroy_node
remove_by_key calls remove_by_pointer
add_clone calls add_pointer
list_finalizer calls destroy_list