destroy_node – flist
destroy_node Subroutine
11 statements
Source File
private impure recursive subroutine destroy_node(me)
destroy the node (and subsequent ones in the list).
Arguments
Type Intent Optional Attributes Name
type(node), pointer :: me
Calls
Called by
Source Code
    impure recursive subroutine destroy_node(me)
    implicit none
    type(node),pointer :: me
    if (associated(me)) then
        call me%destroy()
        call destroy_node(me%next)
        nullify(me%previous)
        deallocate(me)
        nullify(me)
    end if
    end subroutine destroy_node
Call graph
destroy_node calls destroy_node, destroy_node_data
destroy_list calls destroy_node
list_finalizer calls destroy_list